language: node_js
node_js:
  - "10.13.0"
dist: xenial
cache:
  npm: true
matrix:
  fast_finish: true
services:
  - mongodb
install:
  - npm install -g mocha
  - npm install --prefix api
before_script:
  - sleep 15
  - mongo mydb_test --eval 'db.createUser({user:"travis",pwd:"test",roles:["readWrite"]});'
script:
  - npm test --prefix api